export const INDIAN_BANKS = [
  'State Bank of India',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Punjab National Bank',
  'Bank of Baroda',
  'Canara Bank',
  'Union Bank of India',
  'Bank of India',
  'Indian Bank',
  'Central Bank of India',
  'Indian Overseas Bank',
  'UCO Bank',
  'Bank of Maharashtra',
  'Punjab & Sind Bank',
  'Kotak Mahindra Bank',
  'IDBI Bank',
  'Yes Bank',
  'IndusInd Bank',
  'Federal Bank',
  'South Indian Bank',
  'Karnataka Bank',
  'Karur Vysya Bank',
  'City Union Bank',
  'RBL Bank',
  'IDFC FIRST Bank',
  'Tamilnad Mercantile Bank',
  'Dhanlaxmi Bank',
  'CSB Bank',
  'DCB Bank',
  'Bandhan Bank',
  'AU Small Finance Bank',
  'Equitas Small Finance Bank',
  'Ujjivan Small Finance Bank',
  'Suryoday Small Finance Bank',
  'Jana Small Finance Bank',
  'ESAF Small Finance Bank',
  'Kerala Gramin Bank',
  'Kerala State Co-operative Bank',
  'Kerala Bank',
  'Tamil Nadu Mercantile Co-operative Bank',
  'NABARD',
  'India Post Payments Bank',
  'Airtel Payments Bank',
  'Paytm Payments Bank',
  'Fino Payments Bank',
];
